import type { QueryFilter, Types } from 'mongoose';
import { SessionModel, UserModel } from './identity.model.js';
import type { SessionDoc, SessionHydratedDoc, SessionRevokedReason, UserDoc, UserHydratedDoc } from './identity.model.js';

/**
 * The ONLY file in `identity` allowed to touch `UserModel`/`SessionModel`
 * (plan.md §5.4). No business rules here — just reads and writes.
 * Duplicate-key errors, "is this token reused", lockout thresholds, etc.
 * are all decided by `identity.service.ts`; this file just executes the
 * query it's told to.
 */

export type CreateUserInput = Pick<
  UserDoc,
  'email' | 'phone' | 'passwordHash' | 'provider' | 'firstName' | 'lastName' | 'role'
>;

export async function createUser(input: CreateUserInput): Promise<UserHydratedDoc> {
  return UserModel.create(input);
}

export async function findUserByEmail(email: string): Promise<UserHydratedDoc | null> {
  return UserModel.findOne({ email: email.toLowerCase() }).exec();
}

export async function findUserById(id: string): Promise<UserHydratedDoc | null> {
  return UserModel.findById(id).exec();
}

/** `report` module's Customers report (plan.md §11.1's LTV list needs a
 *  name/email per `userId` an `orders` aggregation already grouped by) —
 *  same bulk-by-ids seam as `catalog/brand.service.ts#getBrandsByIds`. */
export async function findUsersByIds(ids: readonly string[]): Promise<UserHydratedDoc[]> {
  return UserModel.find({ _id: { $in: ids } }).exec();
}

export async function countUsers(): Promise<number> {
  return UserModel.countDocuments().exec();
}

export async function findUsersPage(page: number, limit: number): Promise<UserHydratedDoc[]> {
  return UserModel.find()
    .sort({ createdAt: -1 })
    .skip((page - 1) * limit)
    .limit(limit)
    .exec();
}

export async function updateUserRole(id: string, role: UserDoc['role']): Promise<UserHydratedDoc | null> {
  return UserModel.findByIdAndUpdate(id, { role }, { returnDocument: 'after' }).exec();
}

export async function incrementFailedLoginCount(id: string): Promise<UserHydratedDoc | null> {
  return UserModel.findByIdAndUpdate(id, { $inc: { failedLoginCount: 1 } }, { returnDocument: 'after' }).exec();
}

export async function lockUser(id: string, until: Date): Promise<void> {
  await UserModel.updateOne({ _id: id }, { lockedUntil: until }).exec();
}

export async function recordSuccessfulLogin(id: string, ip: string | null): Promise<void> {
  await UserModel.updateOne({ _id: id }, { failedLoginCount: 0, lockedUntil: null, lastLoginAt: new Date(), lastLoginIp: ip }).exec();
}

// ---------------------------------------------------------------------------
// Sessions (refresh tokens)
// ---------------------------------------------------------------------------

export type CreateSessionInput = Pick<SessionDoc, 'userId' | 'family' | 'tokenHash' | 'expiresAt'> &
  Partial<Pick<SessionDoc, 'userAgent' | 'ip'>> & {
    /** Pre-generated by the service so the opaque refresh token (which
     *  embeds the session id) can be constructed in the same step as the
     *  document that stores its hash — no second write to fill it in
     *  after the fact. */
    _id?: Types.ObjectId;
  };

export async function createSession(input: CreateSessionInput): Promise<SessionHydratedDoc> {
  // `exactOptionalPropertyTypes` (plan.md §27.1): omit `_id` entirely
  // rather than pass `_id: undefined` when the caller didn't pre-generate
  // one — Mongoose auto-assigns it either way, but the two are not the
  // same *type* to the compiler.
  return SessionModel.create({
    ...(input._id ? { _id: input._id } : {}),
    userId: input.userId,
    family: input.family,
    tokenHash: input.tokenHash,
    expiresAt: input.expiresAt,
    userAgent: input.userAgent ?? null,
    ip: input.ip ?? null,
  });
}

export async function findSessionById(id: string | Types.ObjectId): Promise<SessionHydratedDoc | null> {
  return SessionModel.findById(id).exec();
}

export async function revokeSession(id: string | Types.ObjectId, reason: SessionRevokedReason): Promise<void> {
  await SessionModel.updateOne({ _id: id, revokedAt: null }, { revokedAt: new Date(), revokedReason: reason }).exec();
}

/**
 * Revokes every not-yet-revoked session in a rotation family. Used both
 * on legitimate logout-all and — the security-critical path — when
 * `identity.service.ts` detects a rotated refresh token being replayed
 * (plan.md §10.1's reuse-detection rule).
 */
export async function revokeFamily(family: string, reason: SessionRevokedReason): Promise<void> {
  await SessionModel.updateMany({ family, revokedAt: null }, { revokedAt: new Date(), revokedReason: reason }).exec();
}

export async function revokeAllSessionsForUser(userId: string, reason: SessionRevokedReason): Promise<void> {
  await SessionModel.updateMany({ userId, revokedAt: null }, { revokedAt: new Date(), revokedReason: reason }).exec();
}

// ---------------------------------------------------------------------------
// Customers — `customer` module's exclusive read/write into `users`
// (plan.md §5.3: never `UserModel` directly). Always scoped to
// `role: 'customer'` — this is the plan.md §11.1 "Customers" screen, not
// "Users & roles"' staff-account list (`findUsersPage`/`updateUserRole`
// above serve that one).
// ---------------------------------------------------------------------------

export interface AdminCustomerFilter {
  search?: string | undefined;
  tag?: string | undefined;
  marketingConsent?: boolean | undefined;
}

/** plan.md doesn't specify per-channel marketing-consent filtering, so
 *  "consented" (`true`) means opted into at least one of email/SMS/
 *  WhatsApp, and "not consented" (`false`) means none — a documented,
 *  single reasonable reading, not a literal transcription. `$and` (rather
 *  than reusing a bare `$or` key twice) is what lets the consent filter
 *  and the free-text search filter coexist in one query without one
 *  silently overwriting the other. */
function buildCustomerQuery(filter: AdminCustomerFilter): QueryFilter<UserDoc> {
  const extraClauses: QueryFilter<UserDoc>[] = [];
  if (filter.marketingConsent === true) {
    extraClauses.push({ $or: [{ 'marketing.email': true }, { 'marketing.sms': true }, { 'marketing.whatsapp': true }] });
  } else if (filter.marketingConsent === false) {
    extraClauses.push({ 'marketing.email': false, 'marketing.sms': false, 'marketing.whatsapp': false });
  }
  if (filter.search) {
    const regex = new RegExp(filter.search.trim(), 'i');
    extraClauses.push({ $or: [{ firstName: regex }, { lastName: regex }, { email: regex }, { 'phone.number': regex }] });
  }

  const query: QueryFilter<UserDoc> = { role: 'customer' };
  if (filter.tag) query.tags = filter.tag;
  if (extraClauses.length > 0) query.$and = extraClauses;
  return query;
}

export async function findCustomersPage(filter: AdminCustomerFilter, page: number, limit: number): Promise<{ docs: UserHydratedDoc[]; total: number }> {
  const query = buildCustomerQuery(filter);
  const [docs, total] = await Promise.all([
    UserModel.find(query)
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(limit)
      .exec(),
    UserModel.countDocuments(query).exec(),
  ]);
  return { docs, total };
}

export async function findCustomerById(id: string): Promise<UserHydratedDoc | null> {
  return UserModel.findOne({ _id: id, role: 'customer' }).exec();
}

export async function updateCustomerTagsAndNotes(id: string, input: { tags?: string[] | undefined; notesInternal?: string | undefined }): Promise<UserHydratedDoc | null> {
  const update: Partial<Pick<UserDoc, 'tags' | 'notesInternal'>> = {};
  if (input.tags !== undefined) update.tags = input.tags;
  if (input.notesInternal !== undefined) update.notesInternal = input.notesInternal;
  return UserModel.findOneAndUpdate({ _id: id, role: 'customer' }, update, { returnDocument: 'after' }).exec();
}

// Otp — stub schema only (see identity.model.ts); the `/auth/otp/*` and
// `/auth/google` routes return 501 in this skeleton, so no repository
// function reads or writes `OtpModel` yet.
