import type { PartialWithUndefined } from '../../shared/types.js';
import { MediaAssetModel } from './media-asset.model.js';
import type { MediaAssetDoc, MediaAssetHydratedDoc } from './media-asset.model.js';

/** The ONLY file allowed to touch `MediaAssetModel` (plan.md §5.4).
 *  `publicId` is required here, not generated by this file — same "the
 *  service layer assigns it, the repository just persists it" split
 *  `menu.repository.ts#MenuItemRepoInput.id` uses; see
 *  `media-asset.service.ts` for the `randomUUID()` call site (mirroring
 *  `catalog/media.service.ts#addProductMedia`'s identical pattern for
 *  product media). */
export type CreateMediaAssetInput = Pick<MediaAssetDoc, 'publicId' | 'url' | 'type'> &
  Partial<Pick<MediaAssetDoc, 'width' | 'height' | 'bytes' | 'alt' | 'altAr' | 'folder' | 'tags' | 'dominantColor'>> &
  Partial<{ uploadedBy: string | null }>;

export type UpdateMediaAssetInput = Partial<Pick<MediaAssetDoc, 'alt' | 'altAr' | 'folder' | 'tags'>>;

const NOT_DELETED = { deletedAt: null };

export async function createMediaAsset(input: CreateMediaAssetInput): Promise<MediaAssetHydratedDoc> {
  return MediaAssetModel.create(input);
}

export async function findMediaAssetById(id: string): Promise<MediaAssetHydratedDoc | null> {
  return MediaAssetModel.findOne({ _id: id, ...NOT_DELETED }).exec();
}

export interface MediaAssetListFilter {
  // `| undefined` explicitly, not just `?:` — callers pass an already
  // Zod-parsed query object straight through (`media-asset.controller.ts`),
  // and `exactOptionalPropertyTypes` (plan.md §27.1) treats "key present
  // with value `undefined`" as distinct from "key omitted" — see
  // `inventory.repository.ts#InventoryListFilter`'s identical comment.
  folder?: string | undefined;
  search?: string | undefined;
  tag?: string | undefined;
  type?: MediaAssetDoc['type'] | undefined;
}

export async function listMediaAssets(filter: MediaAssetListFilter, page: number, limit: number): Promise<{ assets: MediaAssetHydratedDoc[]; total: number }> {
  const query: Record<string, unknown> = { ...NOT_DELETED };
  if (filter.folder !== undefined) query.folder = filter.folder;
  if (filter.tag) query.tags = filter.tag;
  if (filter.type) query.type = filter.type;
  if (filter.search) {
    const regex = new RegExp(filter.search.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
    query.$or = [{ alt: regex }, { altAr: regex }, { folder: regex }, { tags: regex }];
  }
  const [assets, total] = await Promise.all([
    MediaAssetModel.find(query)
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(limit)
      .exec(),
    MediaAssetModel.countDocuments(query).exec(),
  ]);
  return { assets, total };
}

/** Distinct, non-empty folder names — powers a folder-tree/picker UI. */
export async function listDistinctFolders(): Promise<string[]> {
  const folders = await MediaAssetModel.distinct('folder', { ...NOT_DELETED, folder: { $ne: '' } }).exec();
  return (folders as string[]).sort((a, b) => a.localeCompare(b));
}

export async function updateMediaAsset(id: string, input: PartialWithUndefined<UpdateMediaAssetInput>): Promise<MediaAssetHydratedDoc | null> {
  return MediaAssetModel.findOneAndUpdate({ _id: id, ...NOT_DELETED }, input, { returnDocument: 'after' }).exec();
}

export async function bulkUpdateMediaAssets(updates: readonly { id: string; changes: PartialWithUndefined<UpdateMediaAssetInput> }[]): Promise<void> {
  if (updates.length === 0) return;
  await MediaAssetModel.bulkWrite(
    updates.map(({ id, changes }) => ({ updateOne: { filter: { _id: id, ...NOT_DELETED }, update: changes } })),
  );
}

export async function findMediaAssetsByIds(ids: readonly string[]): Promise<MediaAssetHydratedDoc[]> {
  return MediaAssetModel.find({ _id: { $in: ids }, ...NOT_DELETED }).exec();
}

export async function softDeleteMediaAsset(id: string): Promise<boolean> {
  const result = await MediaAssetModel.updateOne({ _id: id, ...NOT_DELETED }, { deletedAt: new Date() }).exec();
  return result.modifiedCount > 0;
}
