import type { ColorFamily, DupattaType, Fabric, Occasion, ProductBadge, Season, Size, StitchingType, Work } from '@lulwah/contracts';

/**
 * Seed data — split from `seed.ts`'s run logic so the data (what gets
 * seeded) stays legible separately from the mechanics (how). Copy is
 * written in the store's voice, matching `apps/web/lib/placeholder-data.ts`
 * — real fabric/work/occasion combinations and invented-but-plausible
 * article codes, not lorem ipsum. A handful of entries (article codes,
 * slugs, colourways) intentionally match that file exactly, per the
 * brief's "so a later swap from placeholder-data to real API calls lines
 * up cleanly."
 */

// ---------------------------------------------------------------------------
// Brands — plan.md §7.3. Slugs match `apps/web/lib/placeholder-data.ts`'s
// `BRANDS` exactly.
// ---------------------------------------------------------------------------
export interface SeedBrand {
  name: string;
  slug: string;
  countryOfOrigin: string;
  description: string;
}

export const BRANDS: SeedBrand[] = [
  { name: 'Khaadi', slug: 'khaadi', countryOfOrigin: 'PK', description: 'Lawn and prêt from Karachi, known for hand-embroidered necklines over digital print.' },
  { name: 'Asim Jofa', slug: 'asim-jofa', countryOfOrigin: 'PK', description: 'Festive and bridal houses of Lahore silk, karandi and banarsi, zari and gota work.' },
  { name: 'Sana Safinaz', slug: 'sana-safinaz', countryOfOrigin: 'PK', description: 'Luxury prêt and lawn with a signature true-to-brand-chart fit, closer to a UK 8 at Small.' },
  { name: 'Maria B', slug: 'maria-b', countryOfOrigin: 'PK', description: 'Formal jamawar and festive chiffon, tilla and dabka on heavy hand-set borders.' },
  { name: 'Gul Ahmed', slug: 'gul-ahmed', countryOfOrigin: 'PK', description: "Pakistan's largest textile house — cambric, khaddar and lawn at everyday prices." },
  { name: 'Elan', slug: 'elan', countryOfOrigin: 'PK', description: 'Organza and banarsi eveningwear, mirror work and hand embroidery for party and nikkah.' },
];

// ---------------------------------------------------------------------------
// Categories — plan.md §7.4's locked taxonomy, transcribed exactly.
// ---------------------------------------------------------------------------
export interface SeedCategoryGroup {
  name: string;
  children?: string[];
}

export const CATEGORY_TAXONOMY: SeedCategoryGroup[] = [
  { name: 'Unstitched', children: ['Lawn', 'Cambric', 'Cotton', 'Khaddar', 'Karandi', 'Linen', 'Chiffon', 'Organza', 'Silk', 'Jacquard', 'Velvet', '1 Piece', '2 Piece', '3 Piece'] },
  { name: 'Pret', children: ['Kurtis', '2 Piece Sets', '3 Piece Sets', 'Co-ords', 'Kaftans'] },
  { name: 'Luxury Pret' },
  { name: 'Festive & Eid' },
  { name: 'Formal & Wedding', children: ['Mehndi', 'Barat', 'Walima', 'Nikkah', 'Guest Wear', 'Shararas', 'Ghararas', 'Lehengas', 'Angrakhas', 'Maxis'] },
  { name: 'Bottoms & Separates', children: ['Trousers', 'Shalwar', 'Culottes', 'Slips'] },
  { name: 'Dupattas & Shawls' },
  { name: 'Accessories', children: ['Clutches', 'Jhumkas & Jewellery', 'Khussa'] },
  { name: 'Sale' },
  { name: 'New In' },
];

// ---------------------------------------------------------------------------
// Products — plan.md brief: "at least 30 products spanning multiple
// stitching types ... fabrics, occasions, and price points." 33 here, 5–6
// per brand, all four stitching types represented, prices from AED 129 to
// AED 1,650.
// ---------------------------------------------------------------------------
export interface SeedVariant {
  sku: string;
  size?: Size;
  color?: string;
  priceFils?: number;
  onHand: number;
}

export interface SeedProduct {
  title: string;
  articleCode: string;
  brandSlug: string;
  categorySlug: string;
  stitchingType: StitchingType;
  pieceCount: 1 | 2 | 3 | null;
  fabric: Fabric;
  secondaryFabrics?: Fabric[];
  work: Work[];
  dupattaType?: DupattaType;
  occasion: Occasion[];
  season: Season;
  colorName: string;
  colorFamily: ColorFamily;
  colorHex: string;
  basePriceFils: number;
  compareAtPriceFils?: number;
  isCustomStitchAvailable?: boolean;
  stitchingPriceFils?: number;
  stitchingLeadDays?: number;
  isFeatured?: boolean;
  isNewIn?: boolean;
  badges?: ProductBadge[];
  variants: SeedVariant[];
  /** Written in the store's voice — plan.md §13.2: "specific copy... not lorem ipsum." */
  descriptionEn: string;
}

export const PRODUCTS: SeedProduct[] = [
  // --- Khaadi -----------------------------------------------------------
  {
    title: 'Ferozi Embroidered Lawn, 3 Piece',
    articleCode: 'KHAS-26-107',
    brandSlug: 'khaadi',
    categorySlug: 'lawn',
    stitchingType: 'unstitched',
    pieceCount: 3,
    fabric: 'lawn',
    work: ['digital_print', 'hand_embroidery'],
    dupattaType: 'chiffon',
    occasion: ['everyday', 'casual'],
    season: 'summer',
    colorName: 'Ferozi',
    colorFamily: 'blue_ferozi',
    colorHex: '#1f7a8c',
    basePriceFils: 24_900,
    isNewIn: true,
    badges: ['new'],
    variants: [
      { sku: 'KHAS-26-107-FZ', color: 'Ferozi', onHand: 0 },
      { sku: 'KHAS-26-107-OW', color: 'Off White', onHand: 0 },
      { sku: 'KHAS-26-107-MG', color: 'Mehndi Green', onHand: 0 },
    ],
    descriptionEn:
      "The shirt front carries a hand-embroidered neckline over Khaadi's signature digital lawn print; the dupatta is chiffon, not the printed cotton this print usually ships with.",
  },
  {
    title: 'Off White Khaddar, 3 Piece',
    articleCode: 'KHAS-25-088',
    brandSlug: 'khaadi',
    categorySlug: 'khaddar',
    stitchingType: 'unstitched',
    pieceCount: 3,
    fabric: 'khaddar',
    work: ['block_print', 'hand_embroidery'],
    dupattaType: 'printed',
    occasion: ['everyday', 'casual'],
    season: 'winter',
    colorName: 'Off White',
    colorFamily: 'white_offwhite',
    colorHex: '#f2efe9',
    basePriceFils: 27_500,
    variants: [{ sku: 'KHAS-25-088-OW', color: 'Off White', onHand: 0 }],
    descriptionEn: 'Khaddar holds heat better than lawn — this is a winter-weight suit, block-printed by hand in Karachi.',
  },
  {
    title: 'Rani Pink Cambric, 2 Piece',
    articleCode: 'KHAS-26-045',
    brandSlug: 'khaadi',
    categorySlug: 'cambric',
    stitchingType: 'unstitched',
    pieceCount: 2,
    fabric: 'cambric',
    work: ['screen_print'],
    dupattaType: 'none',
    occasion: ['everyday'],
    season: 'summer',
    colorName: 'Rani Pink',
    colorFamily: 'pink',
    colorHex: '#c2185b',
    basePriceFils: 13_900,
    variants: [{ sku: 'KHAS-26-045-RP', color: 'Rani Pink', onHand: 22 }],
    descriptionEn: 'Shirt and trouser only, screen-printed on cambric — pair with a dupatta from Dupattas & Shawls or wear the shirt over jeans.',
  },
  {
    title: 'Mint Cotton Net Kurti',
    articleCode: 'KHAS-PRT-26-019',
    brandSlug: 'khaadi',
    categorySlug: 'kurtis',
    stitchingType: 'pret',
    pieceCount: null,
    fabric: 'cotton_net',
    work: ['machine_embroidery'],
    dupattaType: 'none',
    occasion: ['workwear', 'casual'],
    season: 'summer',
    colorName: 'Mint',
    colorFamily: 'green',
    colorHex: '#98d8c8',
    basePriceFils: 16_900,
    variants: [
      { sku: 'KHAS-PRT-26-019-S', size: 'S', onHand: 6 },
      { sku: 'KHAS-PRT-26-019-M', size: 'M', onHand: 9 },
    ],
    descriptionEn: 'A single-piece kurti with an embroidered yoke — true to Khaadi\'s own prêt sizing, not scaled from a Western chart.',
  },
  {
    title: 'Gold Eid Lawn Luxe, 3 Piece',
    articleCode: 'KHAS-EID-26-012',
    brandSlug: 'khaadi',
    categorySlug: 'festive-eid',
    stitchingType: 'unstitched',
    pieceCount: 3,
    fabric: 'lawn',
    work: ['digital_print', 'sequins'],
    dupattaType: 'organza',
    occasion: ['eid', 'festive'],
    season: 'festive',
    colorName: 'Gold',
    colorFamily: 'gold',
    colorHex: '#b8862b',
    basePriceFils: 32_900,
    compareAtPriceFils: 38_900,
    badges: ['limited'],
    variants: [{ sku: 'KHAS-EID-26-012-GD', color: 'Gold', onHand: 4 }],
    descriptionEn: "Khaadi's Eid luxe line — sequin-scattered lawn with an organza dupatta finished on all four sides.",
  },
  {
    title: 'Bridal Silk, Custom Stitched',
    articleCode: 'KHAS-BRD-26-003',
    brandSlug: 'khaadi',
    categorySlug: 'walima',
    stitchingType: 'custom_stitchable',
    pieceCount: 3,
    fabric: 'silk',
    work: ['zari', 'resham'],
    dupattaType: 'silk',
    occasion: ['bridal', 'walima'],
    season: 'festive',
    colorName: 'Deep Maroon',
    colorFamily: 'red_maroon',
    colorHex: '#5c1a2b',
    basePriceFils: 68_000,
    isCustomStitchAvailable: true,
    stitchingPriceFils: 12_000,
    stitchingLeadDays: 10,
    variants: [{ sku: 'KHAS-BRD-26-003-MR', color: 'Deep Maroon', onHand: 2 }],
    descriptionEn: 'Pure silk with hand-set zari and resham on the shirt front. We stitch to your measurements — allow 10 days.',
  },

  // --- Asim Jofa ----------------------------------------------------------
  {
    title: 'Mehndi Green Karandi, 3 Piece',
    articleCode: 'AJ-LAWN-26-3B',
    brandSlug: 'asim-jofa',
    categorySlug: 'karandi',
    stitchingType: 'unstitched',
    pieceCount: 3,
    fabric: 'karandi',
    work: ['zari', 'resham'],
    dupattaType: 'organza',
    occasion: ['festive', 'eid'],
    season: 'festive',
    colorName: 'Mehndi Green',
    colorFamily: 'green',
    colorHex: '#5b6b3a',
    basePriceFils: 42_500,
    badges: ['limited'],
    variants: [{ sku: 'AJ-LAWN-26-3B-MG', color: 'Mehndi Green', onHand: 6 }],
    descriptionEn: 'Zari and resham on karandi — heavier than lawn, cut for festive daywear rather than high-summer heat.',
  },
  {
    title: 'Banarsi Bridal, 3 Piece',
    articleCode: 'AJ-BRD-26-002',
    brandSlug: 'asim-jofa',
    categorySlug: 'walima',
    stitchingType: 'custom_stitchable',
    pieceCount: 3,
    fabric: 'banarsi',
    secondaryFabrics: ['raw_silk'],
    work: ['zari', 'gota', 'sequins'],
    dupattaType: 'silk',
    occasion: ['bridal', 'walima'],
    season: 'festive',
    colorName: 'Deep Maroon',
    colorFamily: 'red_maroon',
    colorHex: '#5c1a2b',
    basePriceFils: 145_000,
    compareAtPriceFils: 165_000,
    isCustomStitchAvailable: true,
    stitchingPriceFils: 15_000,
    stitchingLeadDays: 14,
    badges: ['limited', 'last_pieces'],
    variants: [{ sku: 'AJ-BRD-26-002-MR', color: 'Deep Maroon', onHand: 1 }],
    descriptionEn: 'Woven banarsi with hand-set gota and zari border. One piece left in this colourway — stitching adds 10–14 days.',
  },
  {
    title: 'Chiffon Eid Edit, 3 Piece',
    articleCode: 'AJ-EID-26-021',
    brandSlug: 'asim-jofa',
    categorySlug: 'chiffon',
    stitchingType: 'semi_stitched',
    pieceCount: 3,
    fabric: 'chiffon',
    work: ['digital_print', 'tilla'],
    dupattaType: 'chiffon',
    occasion: ['eid', 'festive'],
    season: 'festive',
    colorName: 'Coral',
    colorFamily: 'red_maroon',
    colorHex: '#e2725b',
    basePriceFils: 38_000,
    variants: [{ sku: 'AJ-EID-26-021-CR', color: 'Coral', onHand: 5 }],
    descriptionEn: 'Shirt front pre-stitched at the neckline — finish the hem to your length. Tilla border on both dupatta edges.',
  },
  {
    title: 'Organza Nikkah Set',
    articleCode: 'AJ-NIK-26-014',
    brandSlug: 'asim-jofa',
    categorySlug: 'nikkah',
    stitchingType: 'custom_stitchable',
    pieceCount: 3,
    fabric: 'organza',
    work: ['hand_embroidery', 'mirror_work'],
    dupattaType: 'organza',
    occasion: ['nikkah', 'party'],
    season: 'festive',
    colorName: 'Emerald',
    colorFamily: 'green',
    colorHex: '#0e3b30',
    basePriceFils: 89_000,
    isCustomStitchAvailable: true,
    stitchingPriceFils: 12_000,
    stitchingLeadDays: 10,
    variants: [{ sku: 'AJ-NIK-26-014-EM', color: 'Emerald', onHand: 3 }],
    descriptionEn: 'Mirror work over hand embroidery on organza, cut for a nikkah guest — stitched to measurement, ready in 10 days.',
  },
  {
    title: 'Silk Jacquard Winter Shawl',
    articleCode: 'AJ-WIN-26-009',
    brandSlug: 'asim-jofa',
    categorySlug: 'dupattas-shawls',
    stitchingType: 'unstitched',
    pieceCount: 1,
    fabric: 'jacquard',
    work: ['naqshi'],
    dupattaType: 'none',
    occasion: ['everyday'],
    season: 'winter',
    colorName: 'Charcoal',
    colorFamily: 'grey_silver',
    colorHex: '#3a3a3a',
    basePriceFils: 18_500,
    variants: [{ sku: 'AJ-WIN-26-009-CH', color: 'Charcoal', onHand: 11 }],
    descriptionEn: 'A single jacquard shawl, woven with a self-tone naqshi border — layers over any winter suit.',
  },

  // --- Sana Safinaz ---------------------------------------------------------
  {
    title: 'Powder Pink Embroidered Kurti',
    articleCode: 'SS-PRET-26-041',
    brandSlug: 'sana-safinaz',
    categorySlug: 'kurtis',
    stitchingType: 'pret',
    pieceCount: null,
    fabric: 'cotton_net',
    work: ['machine_embroidery', 'sequins'],
    dupattaType: 'none',
    occasion: ['workwear', 'casual'],
    season: 'summer',
    colorName: 'Powder Pink',
    colorFamily: 'pink',
    colorHex: '#e7b8c0',
    basePriceFils: 18_900,
    compareAtPriceFils: 21_900,
    badges: ['bestseller'],
    variants: [
      { sku: 'SS-PRET-26-041-XS', size: 'XS', onHand: 0 },
      { sku: 'SS-PRET-26-041-S', size: 'S', onHand: 0 },
      { sku: 'SS-PRET-26-041-M', size: 'M', onHand: 0 },
      { sku: 'SS-PRET-26-041-L', size: 'L', onHand: 0 },
      { sku: 'SS-PRET-26-041-XL', size: 'XL', onHand: 0 },
    ],
    descriptionEn: "A single-piece kurti in Sana Safinaz's standard prêt sizing — true to the brand's own chart, which runs closer to a UK 8 at Small.",
  },
  {
    title: 'Luxury Chiffon Eid, 3 Piece',
    articleCode: 'SS-EID-26-018',
    brandSlug: 'sana-safinaz',
    categorySlug: 'chiffon',
    stitchingType: 'semi_stitched',
    pieceCount: 3,
    fabric: 'chiffon',
    work: ['digital_print', 'sequins'],
    dupattaType: 'chiffon',
    occasion: ['eid', 'festive'],
    season: 'festive',
    colorName: 'Ivory Gold',
    colorFamily: 'gold',
    colorHex: '#c9a24b',
    basePriceFils: 46_000,
    isFeatured: true,
    variants: [{ sku: 'SS-EID-26-018-IG', color: 'Ivory Gold', onHand: 7 }],
    descriptionEn: 'This season\'s Eid luxury edit — sequin placement follows the print, not scattered generically.',
  },
  {
    title: 'Formal Organza Gharara Set',
    articleCode: 'SS-FRM-26-033',
    brandSlug: 'sana-safinaz',
    categorySlug: 'ghararas',
    stitchingType: 'pret',
    pieceCount: null,
    fabric: 'organza',
    work: ['hand_embroidery'],
    dupattaType: 'organza',
    occasion: ['party', 'nikkah'],
    season: 'all_season',
    colorName: 'Wine',
    colorFamily: 'red_maroon',
    colorHex: '#722f37',
    basePriceFils: 58_000,
    variants: [
      { sku: 'SS-FRM-26-033-S', size: 'S', onHand: 3 },
      { sku: 'SS-FRM-26-033-M', size: 'M', onHand: 4 },
    ],
    descriptionEn: 'Fully stitched gharara set, ready to wear — hand embroidery on the shirt front and gharara hem.',
  },
  {
    title: 'Signature Print Lawn, 2 Piece',
    articleCode: 'SS-LAWN-26-004',
    brandSlug: 'sana-safinaz',
    categorySlug: 'lawn',
    stitchingType: 'unstitched',
    pieceCount: 2,
    fabric: 'lawn',
    work: ['digital_print'],
    dupattaType: 'none',
    occasion: ['everyday'],
    season: 'summer',
    colorName: 'Sky Blue',
    colorFamily: 'blue_ferozi',
    colorHex: '#87ceeb',
    basePriceFils: 15_900,
    variants: [{ sku: 'SS-LAWN-26-004-SB', color: 'Sky Blue', onHand: 18 }],
    descriptionEn: "This year's signature print, unstitched shirt and trouser — one of the brand's most-repeated lawn motifs.",
  },
  {
    title: 'Velvet Winter Shawl',
    articleCode: 'SS-WIN-26-051',
    brandSlug: 'sana-safinaz',
    categorySlug: 'dupattas-shawls',
    stitchingType: 'unstitched',
    pieceCount: 1,
    fabric: 'velvet',
    work: ['naqshi'],
    dupattaType: 'none',
    occasion: ['everyday'],
    season: 'winter',
    colorName: 'Bottle Green',
    colorFamily: 'green',
    colorHex: '#2f4f2f',
    basePriceFils: 21_000,
    variants: [{ sku: 'SS-WIN-26-051-BG', color: 'Bottle Green', onHand: 9 }],
    descriptionEn: 'Velvet shawl with a self-embroidered naqshi border — heavier drape than jacquard, for cooler evenings.',
  },
  {
    title: 'Cotton Net Casual Set, 2 Piece',
    articleCode: 'SS-CAS-26-060',
    brandSlug: 'sana-safinaz',
    categorySlug: '2-piece-sets',
    stitchingType: 'pret',
    pieceCount: 2,
    fabric: 'cotton_net',
    work: ['digital_print'],
    dupattaType: 'none',
    occasion: ['casual', 'everyday'],
    season: 'summer',
    colorName: 'Butter Yellow',
    colorFamily: 'yellow_mustard',
    colorHex: '#f3e5ab',
    basePriceFils: 19_500,
    variants: [{ sku: 'SS-CAS-26-060-M', size: 'M', onHand: 12 }],
    descriptionEn: 'Ready-to-wear shirt and trouser set — no dupatta included, styled for a casual daytime look.',
  },

  // --- Maria B --------------------------------------------------------------
  {
    title: 'Royal Blue Jamawar, 3 Piece',
    articleCode: 'MB-FEST-26-019',
    brandSlug: 'maria-b',
    categorySlug: 'walima',
    stitchingType: 'custom_stitchable',
    pieceCount: 3,
    fabric: 'jamawar',
    secondaryFabrics: ['raw_silk'],
    work: ['tilla', 'dabka', 'sequins'],
    dupattaType: 'net',
    occasion: ['barat', 'walima', 'bridal'],
    season: 'festive',
    colorName: 'Royal Blue',
    colorFamily: 'blue_ferozi',
    colorHex: '#1e3a8a',
    basePriceFils: 89_000,
    compareAtPriceFils: 105_000,
    isCustomStitchAvailable: true,
    stitchingPriceFils: 14_000,
    stitchingLeadDays: 12,
    badges: ['limited', 'last_pieces'],
    variants: [
      { sku: 'MB-FEST-26-019-RB', color: 'Royal Blue', onHand: 0 },
      { sku: 'MB-FEST-26-019-WN', color: 'Wine', onHand: 0 },
      { sku: 'MB-FEST-26-019-EM', color: 'Emerald', onHand: 0 },
    ],
    descriptionEn: 'Heavy jamawar with hand-set tilla and dabka on the shirt front and border. We stitch to your measurements — allow 10–14 days.',
  },
  {
    title: 'Mustard Chiffon, 2 Piece',
    articleCode: 'MB-FEST-26-071',
    brandSlug: 'maria-b',
    categorySlug: 'chiffon',
    stitchingType: 'semi_stitched',
    pieceCount: 2,
    fabric: 'chiffon',
    work: ['digital_print', 'sequins'],
    dupattaType: 'chiffon',
    occasion: ['festive', 'party'],
    season: 'festive',
    colorName: 'Mustard',
    colorFamily: 'yellow_mustard',
    colorHex: '#c99a2e',
    basePriceFils: 21_900,
    badges: ['new'],
    variants: [{ sku: 'MB-FEST-26-071-MU', color: 'Mustard', onHand: 9 }],
    descriptionEn: 'Shirt front is pre-stitched at the neckline and sides — finish the hem and sleeves to your length.',
  },
  {
    title: 'Classic Lawn, 3 Piece',
    articleCode: 'MB-LAWN-26-102',
    brandSlug: 'maria-b',
    categorySlug: 'lawn',
    stitchingType: 'unstitched',
    pieceCount: 3,
    fabric: 'lawn',
    work: ['digital_print'],
    dupattaType: 'printed',
    occasion: ['everyday', 'casual'],
    season: 'summer',
    colorName: 'Terracotta',
    colorFamily: 'brown_beige',
    colorHex: '#c66b3d',
    basePriceFils: 17_500,
    variants: [{ sku: 'MB-LAWN-26-102-TC', color: 'Terracotta', onHand: 26 }],
    descriptionEn: "Maria B's everyday print line — matching printed dupatta, no embroidery, priced for the summer rotation.",
  },
  {
    title: 'Eid Luxury Organza, 3 Piece',
    articleCode: 'MB-EID-26-036',
    brandSlug: 'maria-b',
    categorySlug: 'festive-eid',
    stitchingType: 'semi_stitched',
    pieceCount: 3,
    fabric: 'organza',
    work: ['hand_embroidery', 'sequins'],
    dupattaType: 'organza',
    occasion: ['eid', 'festive'],
    season: 'festive',
    colorName: 'Blush',
    colorFamily: 'pink',
    colorHex: '#f4c2c2',
    basePriceFils: 52_000,
    compareAtPriceFils: 61_000,
    variants: [{ sku: 'MB-EID-26-036-BL', color: 'Blush', onHand: 3 }],
    descriptionEn: "The brand's Eid luxury organza — hand-embroidered panels on the shirt front, sequins along the dupatta border.",
  },
  {
    title: 'Bridal Silk Gharara',
    articleCode: 'MB-BRD-26-008',
    brandSlug: 'maria-b',
    categorySlug: 'nikkah',
    stitchingType: 'custom_stitchable',
    pieceCount: 3,
    fabric: 'silk',
    work: ['zari', 'gota'],
    dupattaType: 'silk',
    occasion: ['bridal', 'nikkah'],
    season: 'festive',
    colorName: 'Champagne Gold',
    colorFamily: 'gold',
    colorHex: '#d4af37',
    basePriceFils: 112_000,
    isCustomStitchAvailable: true,
    stitchingPriceFils: 15_000,
    stitchingLeadDays: 14,
    variants: [{ sku: 'MB-BRD-26-008-CG', color: 'Champagne Gold', onHand: 2 }],
    descriptionEn: 'Pure silk gharara set with hand-set zari and gota border, stitched to measurement for your nikkah.',
  },
  {
    title: 'Karandi Festive, 3 Piece',
    articleCode: 'MB-KAR-26-044',
    brandSlug: 'maria-b',
    categorySlug: 'karandi',
    stitchingType: 'unstitched',
    pieceCount: 3,
    fabric: 'karandi',
    work: ['resham', 'tilla'],
    dupattaType: 'chiffon',
    occasion: ['festive', 'mehndi'],
    season: 'festive',
    colorName: 'Rust',
    colorFamily: 'brown_beige',
    colorHex: '#a65c32',
    basePriceFils: 33_500,
    variants: [{ sku: 'MB-KAR-26-044-RU', color: 'Rust', onHand: 6 }],
    descriptionEn: 'Resham and tilla on karandi, a mehndi-weight fabric that holds embroidery better than lawn.',
  },

  // --- Gul Ahmed --------------------------------------------------------------
  {
    title: 'Ivory Cambric, 2 Piece',
    articleCode: 'GA-SUM-26-233',
    brandSlug: 'gul-ahmed',
    categorySlug: 'cambric',
    stitchingType: 'unstitched',
    pieceCount: 2,
    fabric: 'cambric',
    work: ['screen_print'],
    dupattaType: 'none',
    occasion: ['everyday'],
    season: 'summer',
    colorName: 'Ivory',
    colorFamily: 'white_offwhite',
    colorHex: '#f4efe6',
    basePriceFils: 12_900,
    compareAtPriceFils: 15_900,
    variants: [{ sku: 'GA-SUM-26-233-IV', color: 'Ivory', onHand: 31 }],
    descriptionEn: 'Shirt and trouser only — pair with a dupatta from Dupattas & Shawls, or wear as a kurti over jeans.',
  },
  {
    title: 'Khaddar Winter, 3 Piece',
    articleCode: 'GA-WIN-26-077',
    brandSlug: 'gul-ahmed',
    categorySlug: 'khaddar',
    stitchingType: 'unstitched',
    pieceCount: 3,
    fabric: 'khaddar',
    work: ['block_print'],
    dupattaType: 'printed',
    occasion: ['everyday', 'casual'],
    season: 'winter',
    colorName: 'Charcoal',
    colorFamily: 'grey_silver',
    colorHex: '#3a3a3a',
    basePriceFils: 16_500,
    variants: [{ sku: 'GA-WIN-26-077-CH', color: 'Charcoal', onHand: 14 }],
    descriptionEn: 'Khaddar shirt, trouser and printed cotton dupatta — Gul Ahmed\'s winter-weight everyday line.',
  },
  {
    title: 'Eid Lawn Deluxe, 3 Piece',
    articleCode: 'GA-EID-26-015',
    brandSlug: 'gul-ahmed',
    categorySlug: 'festive-eid',
    stitchingType: 'unstitched',
    pieceCount: 3,
    fabric: 'lawn',
    work: ['digital_print', 'hand_embroidery'],
    dupattaType: 'chiffon',
    occasion: ['eid', 'festive'],
    season: 'festive',
    colorName: 'Peach',
    colorFamily: 'pink',
    colorHex: '#ffcba4',
    basePriceFils: 26_500,
    compareAtPriceFils: 31_000,
    badges: ['bestseller'],
    variants: [{ sku: 'GA-EID-26-015-PC', color: 'Peach', onHand: 8 }],
    descriptionEn: "Gul Ahmed's Eid deluxe line — hand-embroidered neckline over digital print, chiffon dupatta.",
  },
  {
    title: 'Pret Co-ord Set',
    articleCode: 'GA-PRT-26-091',
    brandSlug: 'gul-ahmed',
    categorySlug: 'co-ords',
    stitchingType: 'pret',
    pieceCount: null,
    fabric: 'cotton',
    work: ['screen_print'],
    dupattaType: 'none',
    occasion: ['casual', 'workwear'],
    season: 'summer',
    colorName: 'Sage',
    colorFamily: 'green',
    colorHex: '#9caf88',
    basePriceFils: 14_900,
    variants: [
      { sku: 'GA-PRT-26-091-S', size: 'S', onHand: 5 },
      { sku: 'GA-PRT-26-091-M', size: 'M', onHand: 7 },
    ],
    descriptionEn: 'Matching top and trouser co-ord, cotton with a screen-printed border — no dupatta needed.',
  },
  {
    title: 'Organza Party Wear',
    articleCode: 'GA-PTY-26-028',
    brandSlug: 'gul-ahmed',
    categorySlug: 'guest-wear',
    stitchingType: 'pret',
    pieceCount: null,
    fabric: 'organza',
    work: ['sequins', 'hand_embroidery'],
    dupattaType: 'organza',
    occasion: ['party', 'nikkah'],
    season: 'all_season',
    colorName: 'Navy',
    colorFamily: 'blue_ferozi',
    colorHex: '#1b263b',
    basePriceFils: 29_900,
    variants: [{ sku: 'GA-PTY-26-028-NV', color: 'Navy', onHand: 6 }],
    descriptionEn: 'Fully stitched party set, sequin placement along the neckline and hem — ready to wear.',
  },

  // --- Elan -------------------------------------------------------------------
  {
    title: 'Noir Organza Gharara Set',
    articleCode: 'ELN-BRD-26-006',
    brandSlug: 'elan',
    categorySlug: 'ghararas',
    stitchingType: 'pret',
    pieceCount: null,
    fabric: 'organza',
    work: ['hand_embroidery', 'mirror_work'],
    dupattaType: 'organza',
    occasion: ['nikkah', 'party'],
    season: 'all_season',
    colorName: 'Noir',
    colorFamily: 'black',
    colorHex: '#131311',
    basePriceFils: 68_000,
    compareAtPriceFils: 76_000,
    badges: ['bestseller'],
    variants: [{ sku: 'ELN-BRD-26-006-NR', color: 'Noir', size: 'M', onHand: 5 }],
    descriptionEn: "Mirror work over hand embroidery on a fully-stitched gharara set — Elan's standard formal sizing, ready to wear.",
  },
  {
    title: 'Luxury Lawn Eid, 3 Piece',
    articleCode: 'ELN-EID-26-011',
    brandSlug: 'elan',
    categorySlug: 'festive-eid',
    stitchingType: 'unstitched',
    pieceCount: 3,
    fabric: 'lawn',
    work: ['digital_print', 'tilla'],
    dupattaType: 'organza',
    occasion: ['eid', 'festive'],
    season: 'festive',
    colorName: 'Cobalt',
    colorFamily: 'blue_ferozi',
    colorHex: '#0047ab',
    basePriceFils: 34_000,
    variants: [{ sku: 'ELN-EID-26-011-CB', color: 'Cobalt', onHand: 7 }],
    descriptionEn: "Elan's Eid luxury lawn — tilla border on an organza dupatta, digital print exclusive to this drop.",
  },
  {
    title: 'Bridal Banarsi Set',
    articleCode: 'ELN-BRD-26-019',
    brandSlug: 'elan',
    categorySlug: 'barat',
    stitchingType: 'custom_stitchable',
    pieceCount: 3,
    fabric: 'banarsi',
    work: ['zari', 'dabka', 'gota'],
    dupattaType: 'silk',
    occasion: ['bridal', 'walima'],
    season: 'festive',
    colorName: 'Wine',
    colorFamily: 'red_maroon',
    colorHex: '#5c1a2b',
    basePriceFils: 138_000,
    isCustomStitchAvailable: true,
    stitchingPriceFils: 15_000,
    stitchingLeadDays: 14,
    badges: ['limited'],
    variants: [{ sku: 'ELN-BRD-26-019-WN', color: 'Wine', onHand: 2 }],
    descriptionEn: 'Woven banarsi with hand-set zari, dabka and gota — Elan\'s barat line, stitched to measurement.',
  },
  {
    title: 'Chiffon Formal, 2 Piece',
    articleCode: 'ELN-FRM-26-025',
    brandSlug: 'elan',
    categorySlug: 'mehndi',
    stitchingType: 'semi_stitched',
    pieceCount: 2,
    fabric: 'chiffon',
    work: ['sequins', 'hand_embroidery'],
    dupattaType: 'chiffon',
    occasion: ['party', 'mehndi'],
    season: 'all_season',
    colorName: 'Fuchsia',
    colorFamily: 'pink',
    colorHex: '#c2185b',
    basePriceFils: 31_500,
    variants: [{ sku: 'ELN-FRM-26-025-FU', color: 'Fuchsia', onHand: 4 }],
    descriptionEn: 'Pre-stitched neckline and sides, hand embroidery scattered across the shirt front — finish to your length.',
  },
  {
    title: 'Velvet Winter Shawl',
    articleCode: 'ELN-WIN-26-003',
    brandSlug: 'elan',
    categorySlug: 'dupattas-shawls',
    stitchingType: 'unstitched',
    pieceCount: 1,
    fabric: 'velvet',
    work: ['naqshi'],
    dupattaType: 'none',
    occasion: ['everyday'],
    season: 'winter',
    colorName: 'Plum',
    colorFamily: 'purple',
    colorHex: '#5c2a4d',
    basePriceFils: 19_900,
    variants: [{ sku: 'ELN-WIN-26-003-PL', color: 'Plum', onHand: 0 }],
    descriptionEn: 'Velvet shawl with a tonal naqshi border, sold on its own — layers over any winter suit.',
  },
];
